/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:61a8338c-d5dd-4fa6-8775-304e8b4a9ac8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qn8y8Ky6x",
    "aws_user_pools_web_client_id": "57haoc03s3sooq7ioirnt56iek",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wq6qqvpoirhzfhlf4dxktj5kue.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
